name: YoutubeDump

on: [push]

env: 
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: initialization environment
      id: initialization
      run: |
        sudo wget https://yt-dl.org/downloads/latest/youtube-dl --no-check-certificate -O /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
        sudo apt install -y ffmpeg zip
        sudo timedatectl set-timezone "$TZ"

    - name: download videos
      if: success() && !cancelled()
      run: |
        mkdir videos
        cd videos
        youtube-dl --merge-output-format mp4 -f bestvideo[ext=mp4][height<=?1080]+bestaudio[ext=m4a] --write-auto-sub $(cat ../url.txt)

    - name: organize files
      if: success() && !cancelled()
      run: |
        zip -s 1900m -9 videos-"$(date '+%F')".zip videos/*

    - name: Upload firmware to WeTransfer
      id: wetransfer
      if: success() && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -p 16 --no-progress videos-"$(date '+%F')".* 2>&1 | tee wetransfer.log
        links=($(cat wetransfer.log | grep https.* -o))
        for link in ${links[*]}
        do
          echo "::warning file=wetransfer.com::Download Link: $link"
          echo "::set-output name=url::Download Link: $link"
        done
